### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [cjkelling/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [ ] I made one initial commit. `Made multiple`
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [ ] I broke down larger processes into smaller layers.
`We would like to see multiple layers to each process. These problems need to be broken down into steps that cannot be broken down further.`
- [ ] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
`present tense verb`
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
`Did not choose methods that modify attributes`
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message.
`Multiple commits named Initial Commit`

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 
`Multiple commits named Initial Commit`

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
`data needs to be specified - attribute cannot be either integer or float, but needs to be one in particular.`
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
`These do represent methods or actions, but some of them are from the point of view of a person such as sit, work on and draw on. The idea here is that the methods represent behaviors of the actual desk - not the person around the desk, which in this case isn't easy, but you could have methods such as roll, open_drawer, close_drawer, rise, lower.`
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
`methods do not modify attributes`
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message.
`Multiple commits named Initial Commit`

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
`A result would be something concrete, such as a change in height or color.`
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
`Multiple commits named Initial Commit`

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
